### ISSUE TITLE
ID, Password field not captured

### ISSUE THREAD

**Issue by mjkim610** [mjkim610/eagle#1]
In some sites like yscec.yonsei.ac.kr the id and password fields are not captured.
![image](https://cloud.githubusercontent.com/assets/17107206/16754370/1b643840-482d-11e6-8e29-14b2c38108aa.png)

**Comment by gyen92** [comment]
**nothing captured in sites below**
maplestory.nexon.com
www.daum.net
![1](https://cloud.githubusercontent.com/assets/11654678/16756485/73c3689e-47d3-11e6-85c2-78108d7e237d.JPG)

*Naver, when the user fail to login, it still captures the history with password, however, it doesn't capture password when the user success to login

**Comment by gyen92** [comment]
login not caputed in:
www.wemakeprice.com

---

login captured in:
www.naver.com
www.daum.net
www.facebook.com
www.github.com
mosaic.mcmaster.ca
www.gmarket.com
www.amazon.ca
www.ebay.ca
www.8tracks.com

**Comment by mjkim610** [comment]
11st.co.kr has inline JavaScript which is fired at onclick of the login button. It encrypted the username and password, stores them in a separate element and clears the original, unencrypted username and password. Because the extension's onclick event is fired after this one, the extension captures two empty input fields.
