### ISSUE TITLE
The home.html page does not update

### ISSUE THREAD

**Issue by mjkim610** [mjkim610/eagle#2]
When the home.html tab is open, clicking on the extension icon does not update the home.html file.
It will be better to update the page when the icon is clicked.

**Comment by gyen92** [comment]
For me, it keeps opening a new tab with updated log history while the previous tab is not closed neither.

**Comment by gyen92** [comment]
It updates home.html by clicking the icon however still doesn't focus the tab.

**Comment by gyen92** [comment]
It focuses on both home.html tab and window.
